export const de = {
  appName: "Salawat Circle",
  commonContinue: "Weiter",
  commonSave: "Speichern",
  commonUnavailable: "In diesem MVP noch nicht verfügbar",
  tabsToday: "Heute",
  tabsGroups: "Gruppen",
  tabsSettings: "Einstellungen",
  welcomeEyebrow: "Privat und datensparsam",
  welcomeTitle: "Salawat bewusst festhalten",
  welcomeBody:
    "Erfasse deine persönlichen Werte und teile nur freiwillig zusammengefasste Zahlen in privaten Gruppen.",
  welcomeAction: "Anmeldung beginnen",
  authEmailTitle: "E-Mail-Adresse",
  authEmailLabel: "E-Mail-Adresse",
  authEmailHint: "Wir senden dir einen einmaligen Anmeldecode.",
  authEmailAction: "Weiter zum Code",
  authCodeTitle: "Einmalcode",
  authCodeLabel: "Sechsstelliger Code",
  authCodeHint: "Der Code ist zehn Minuten gültig.",
  authCodeResend: "Neuen Code anfordern",
  profileTitle: "Dein Profil",
  profileNameLabel: "Anzeigename",
  profileTimezoneLabel: "Zeitzone",
  consentTitle: "Einwilligung",
  consentLabel:
    "Ich willige in die Verarbeitung meiner persönlichen Einträge ein.",
  consentHint: "Die Gruppenteilung bleibt freiwillig.",
  todayHeading: "Heute erfasst",
  todayAddLabel: "Salawat hinzufügen",
  todayAddHint: "Gib eine ganze Zahl ein.",
  todaySubmit: "Eintragen",
  todayDashboard: "Übersicht",
  todayTotal: "Gesamt",
  todayWeek: "Diese Woche",
  todayGoal: "Tagesziel",
  todayGoalDays: "Ziel erreicht",
  todayNoGoal: "Kein Ziel",
  todayNoGoalDay: "Noch kein Zieltag",
  todayHistory: "Verlauf",
  todayHistoryEmpty: "Noch keine Einträge vorhanden.",
  entryEditTitle: "Eintrag bearbeiten",
  entryAmountLabel: "Betrag",
  entryDateLabel: "Datum",
  groupsCreate: "Gruppe erstellen",
  groupsEmptyTitle: "Noch keine Gruppe",
  groupsEmptyBody:
    "Du bist noch in keiner Gruppe. Erstelle eine private Gruppe oder tritt über einen Einladungslink bei.",
  groupCreateTitle: "Gruppe erstellen",
  groupNameLabel: "Gruppenname",
  groupTitle: "Private Gruppe",
  groupRanking: "Rangliste",
  groupMembers: "Mitglieder verwalten",
  groupInvites: "Einladungen verwalten",
  groupMembersTitle: "Mitglieder",
  groupInvitesTitle: "Einladungen",
  joinTitle: "Einladung prüfen",
  joinBody: "Prüfe die Gruppeninformationen, bevor du freiwillig beitrittst.",
  joinAction: "Einladung annehmen",
  settingsLanguage: "Sprache",
  settingsLanguageHint: "Sprache dieser App",
  settingsLanguageSystem: "Systemstandard",
  settingsLanguageGerman: "Deutsch",
  settingsLanguageEnglish: "English",
  settingsProfile: "Profil",
  settingsReminder: "Tägliche Erinnerung",
  settingsPrivacy: "Datenschutz",
  settingsLegal: "Rechtliches",
  settingsSupport: "Hilfe und Support",
  reminderTitle: "Tägliche Erinnerung",
  reminderTimeLabel: "Uhrzeit",
  privacyTitle: "Datenschutz",
  privacyExport: "Daten exportieren",
  privacyDelete: "Konto löschen",
  legalTitle: "Rechtliches",
  legalPrivacy: "Datenschutzerklärung",
  legalTerms: "Nutzungsbedingungen",
  legalImprint: "Impressum",
  supportTitle: "Hilfe und Support",
  supportReport: "Problem melden",
  supportContact: "Kontakt aufnehmen",
  stateLoadingTitle: "Wird geladen",
  stateLoadingBody: "Einen Moment bitte.",
  stateEmptyTitle: "Noch keine Inhalte",
  stateEmptyBody: "Hier erscheint etwas, sobald Daten vorhanden sind.",
  stateOfflineWithDataTitle: "Offline",
  stateOfflineWithDataBody: "Du siehst den zuletzt gespeicherten Stand.",
  stateOfflineEmptyTitle: "Offline und noch keine Daten",
  stateOfflineEmptyBody: "Stelle eine Verbindung her und versuche es erneut.",
  statePendingTitle: "Wird synchronisiert",
  statePendingBody: "Deine Änderung bleibt sicher auf diesem Gerät.",
  statePartialErrorTitle: "Nicht alles konnte geladen werden",
  statePartialErrorBody: "Die vorhandenen Inhalte bleiben sichtbar.",
  stateErrorTitle: "Verbindung nicht möglich",
  stateErrorBody: "Versuche es in einem Moment erneut.",
  stateForbiddenTitle: "Kein Zugriff",
  stateForbiddenBody: "Du darfst diesen Inhalt nicht öffnen.",
  stateSessionExpiredTitle: "Sitzung abgelaufen",
  stateSessionExpiredBody: "Melde dich erneut an.",
  stateMaintenanceTitle: "Wartung läuft",
  stateMaintenanceBody: "Salawat Circle ist bald wieder verfügbar.",
  stateUpgradeRequiredTitle: "Aktualisierung erforderlich",
  stateUpgradeRequiredBody: "Aktualisiere die App, um fortzufahren.",
  notFoundTitle: "Seite nicht gefunden",
  notFoundBody: "Diese Seite ist nicht verfügbar.",
  notFoundAction: "Zur Willkommensseite",
} as const;
export type TranslationKey = keyof typeof de;
