export const de = {
  appName: "Salawat Circle",
  commonContinue: "Weiter",
  commonSave: "Speichern",
  commonUnavailable: "In diesem MVP noch nicht verfügbar",
  tabsToday: "Heute",
  tabsGroups: "Gruppen",
  tabsSettings: "Einstellungen",
  welcomeEyebrow: "Privat und datensparsam",
  welcomeTitle: "Salawat bewusst festhalten",
  welcomeBody:
    "Erfasse deine persönlichen Werte und teile nur freiwillig zusammengefasste Zahlen in privaten Gruppen.",
  welcomeAction: "Anmeldung beginnen",
  authEmailTitle: "E-Mail-Adresse",
  authEmailLabel: "E-Mail-Adresse",
  authEmailHint: "Wir senden dir einen einmaligen Anmeldecode.",
  authEmailAction: "Weiter zum Code",
  authEmailInvalid: "Gib eine gültige E-Mail-Adresse ein.",
  authRequestFailed:
    "Der Code konnte nicht angefordert werden. Versuche es später erneut.",
  authCodeTitle: "Einmalcode",
  authCodeLabel: "Sechsstelliger Code",
  authCodeHint: "Der Code ist zehn Minuten gültig.",
  authCodeSent:
    "Wenn die Adresse verwendet werden kann, wurde ein Anmeldecode gesendet.",
  authCodeAction: "Code prüfen",
  authCodeInvalid: "Der Code ist ungültig oder nicht mehr gültig.",
  authCodeResend: "Neuen Code anfordern",
  authCodeResendIn: "Erneut anfordern in",
  profileTitle: "Dein Profil",
  profileNameLabel: "Anzeigename",
  profileNameHint: "Zwischen 2 und 30 Zeichen.",
  profileNameInvalid: "Der Anzeigename muss 2 bis 30 Zeichen lang sein.",
  profileTimezoneLabel: "Zeitzone",
  profileTimezoneHint: "Automatisch als IANA-Zeitzone erkannt.",
  profileSaveFailed: "Das Profil konnte nicht gespeichert werden.",
  consentTitle: "Einwilligung",
  consentBody:
    "Salawat Circle verarbeitet deinen Anzeigenamen, deine Zeitzone und deine persönlichen Salawat-Einträge, um dein privates Konto und deine Statistiken bereitzustellen. Diese Einwilligung umfasst keine Freigabe an Gruppen; darüber entscheidest du bei jedem Beitritt getrennt.",
  consentLabel:
    "Ich willige in die Verarbeitung meiner persönlichen Einträge ein.",
  consentHint: "Die Gruppenteilung bleibt freiwillig.",
  consentSaveFailed: "Die Einwilligung konnte nicht gespeichert werden.",
  todayHeading: "Heute erfasst",
  todayAddLabel: "Salawat hinzufügen",
  todayAddHint: "Gib eine ganze Zahl ein.",
  todaySubmit: "Eintragen",
  todayDashboard: "Übersicht",
  todayTotal: "Gesamt",
  todayWeek: "Diese Woche",
  todayGoal: "Tagesziel",
  todayGoalDays: "Ziel erreicht",
  todayNoGoal: "Kein Ziel",
  todayNoGoalDay: "Noch kein Zieltag",
  todayHistory: "Verlauf",
  todayHistoryEmpty: "Noch keine Einträge vorhanden.",
  goalTitle: "Tagesziel",
  goalSliderLabel: "Tagesziel-Regler",
  goalSliderHint: "Passe das Tagesziel in 100er-Schritten bis 10.000 an.",
  goalAmountLabel: "Zielwert",
  goalAmountHint: "Gib eine ganze Zahl von 1 bis 10.000.000 ein.",
  goalSave: "Ziel speichern",
  goalClear: "Ziel deaktivieren",
  goalSaveFailed: "Das Tagesziel konnte nicht gespeichert werden. Versuche es erneut.",
  historyLoadMore: "Weitere Einträge laden",
  historyLoadFailed: "Weitere Einträge konnten nicht geladen werden.",
  historyEnd: "Alle Einträge geladen.",
  entryEditTitle: "Eintrag bearbeiten",
  entryAmountLabel: "Betrag",
  entryAmountInvalid: "Gib eine ganze Zahl von 1 bis 10.000.000 ein.",
  entryDateLabel: "Datum",
  entryDateInvalid: "Wähle ein Datum von heute oder höchstens 365 Tage davor.",
  entrySaveFailed: "Der Eintrag konnte nicht gespeichert werden. Versuche es erneut.",
  entryConflict:
    "Dieser Eintrag wurde auf einem anderen Gerät geändert. Lade den Verlauf neu und prüfe den aktuellen Stand.",
  entryToday: "Heute",
  entryYesterday: "Gestern",
  entryEdit: "Bearbeiten",
  entryDelete: "Löschen",
  entryDeleteTitle: "Eintrag löschen?",
  entryDeleteBody: "Dieser Eintrag wird endgültig gelöscht.",
  entryDeleteConfirm: "Löschen",
  commonCancel: "Abbrechen",
  groupsCreate: "Gruppe erstellen",
  groupsEmptyTitle: "Noch keine Gruppe",
  groupsEmptyBody:
    "Du bist noch in keiner Gruppe. Erstelle eine private Gruppe oder tritt über einen Einladungslink bei.",
  groupCreateTitle: "Gruppe erstellen",
  groupNameLabel: "Gruppenname",
  groupTitle: "Private Gruppe",
  groupRanking: "Rangliste",
  groupMembers: "Mitglieder verwalten",
  groupInvites: "Einladungen verwalten",
  groupMembersTitle: "Mitglieder",
  groupInvitesTitle: "Einladungen",
  joinTitle: "Einladung prüfen",
  joinBody: "Prüfe die Gruppeninformationen, bevor du freiwillig beitrittst.",
  joinAction: "Einladung annehmen",
  settingsLanguage: "Sprache",
  settingsLanguageHint: "Sprache dieser App",
  settingsLanguageSystem: "Systemstandard",
  settingsLanguageGerman: "Deutsch",
  settingsLanguageEnglish: "English",
  settingsProfile: "Profil",
  settingsReminder: "Tägliche Erinnerung",
  settingsPrivacy: "Datenschutz",
  settingsLegal: "Rechtliches",
  settingsSupport: "Hilfe und Support",
  settingsSignOut: "Abmelden",
  settingsSignOutFailed: "Die lokalen Kontodaten konnten nicht vollständig gelöscht werden.",
  reminderTitle: "Tägliche Erinnerung",
  reminderTimeLabel: "Uhrzeit",
  privacyTitle: "Datenschutz",
  privacyExport: "Daten exportieren",
  privacyDelete: "Konto löschen",
  legalTitle: "Rechtliches",
  legalPrivacy: "Datenschutzerklärung",
  legalTerms: "Nutzungsbedingungen",
  legalImprint: "Impressum",
  supportTitle: "Hilfe und Support",
  supportReport: "Problem melden",
  supportContact: "Kontakt aufnehmen",
  stateLoadingTitle: "Wird geladen",
  stateLoadingBody: "Einen Moment bitte.",
  stateEmptyTitle: "Noch keine Inhalte",
  stateEmptyBody: "Hier erscheint etwas, sobald Daten vorhanden sind.",
  stateOfflineWithDataTitle: "Offline",
  stateOfflineWithDataBody: "Du siehst den zuletzt gespeicherten Stand.",
  stateOfflineEmptyTitle: "Offline und noch keine Daten",
  stateOfflineEmptyBody: "Stelle eine Verbindung her und versuche es erneut.",
  statePendingTitle: "Wird synchronisiert",
  statePendingBody: "Deine Änderung bleibt sicher auf diesem Gerät.",
  statePartialErrorTitle: "Nicht alles konnte geladen werden",
  statePartialErrorBody: "Die vorhandenen Inhalte bleiben sichtbar.",
  stateErrorTitle: "Verbindung nicht möglich",
  stateErrorBody: "Versuche es in einem Moment erneut.",
  stateForbiddenTitle: "Kein Zugriff",
  stateForbiddenBody: "Du darfst diesen Inhalt nicht öffnen.",
  stateSessionExpiredTitle: "Sitzung abgelaufen",
  stateSessionExpiredBody: "Melde dich erneut an.",
  stateMaintenanceTitle: "Wartung läuft",
  stateMaintenanceBody: "Salawat Circle ist bald wieder verfügbar.",
  stateUpgradeRequiredTitle: "Aktualisierung erforderlich",
  stateUpgradeRequiredBody: "Aktualisiere die App, um fortzufahren.",
  notFoundTitle: "Seite nicht gefunden",
  notFoundBody: "Diese Seite ist nicht verfügbar.",
  notFoundAction: "Zur Willkommensseite",
} as const;
export type TranslationKey = keyof typeof de;
