export const de = {
  appName: "Salawat Circle",
  commonContinue: "Weiter",
  commonSave: "Speichern",
  commonUnavailable: "In diesem MVP noch nicht verfügbar",
  tabsToday: "Heute",
  tabsGroups: "Gruppen",
  tabsSettings: "Einstellungen",
  welcomeEyebrow: "Privat und datensparsam",
  welcomeTitle: "Salawat bewusst festhalten",
  welcomeBody:
    "Erfasse deine persönlichen Werte und teile nur freiwillig zusammengefasste Zahlen in privaten Gruppen.",
  welcomeAction: "Anmeldung beginnen",
  authEmailTitle: "E-Mail-Adresse",
  authEmailLabel: "E-Mail-Adresse",
  authEmailHint: "Wir senden dir einen einmaligen Anmeldecode.",
  authEmailAction: "Weiter zum Code",
  authEmailInvalid: "Gib eine gültige E-Mail-Adresse ein.",
  authRequestFailed:
    "Der Code konnte nicht angefordert werden. Versuche es später erneut.",
  authCodeTitle: "Einmalcode",
  authCodeLabel: "Sechsstelliger Code",
  authCodeHint: "Der Code ist zehn Minuten gültig.",
  authCodeSent:
    "Wenn die Adresse verwendet werden kann, wurde ein Anmeldecode gesendet.",
  authCodeAction: "Code prüfen",
  authCodeInvalid: "Der Code ist ungültig oder nicht mehr gültig.",
  authCodeResend: "Neuen Code anfordern",
  authCodeResendIn: "Erneut anfordern in",
  profileTitle: "Dein Profil",
  profileNameLabel: "Anzeigename",
  profileNameHint: "Zwischen 2 und 30 Zeichen.",
  profileNameInvalid: "Der Anzeigename muss 2 bis 30 Zeichen lang sein.",
  profileTimezoneLabel: "Zeitzone",
  profileTimezoneHint: "Automatisch als IANA-Zeitzone erkannt.",
  profileSaveFailed: "Das Profil konnte nicht gespeichert werden.",
  consentTitle: "Einwilligung",
  consentBody:
    "Salawat Circle verarbeitet deinen Anzeigenamen, deine Zeitzone und deine persönlichen Salawat-Einträge, um dein privates Konto und deine Statistiken bereitzustellen. Diese Einwilligung umfasst keine Freigabe an Gruppen; darüber entscheidest du bei jedem Beitritt getrennt.",
  consentLabel:
    "Ich willige in die Verarbeitung meiner persönlichen Einträge ein.",
  consentHint: "Die Gruppenteilung bleibt freiwillig.",
  consentSaveFailed: "Die Einwilligung konnte nicht gespeichert werden.",
  todayHeading: "Heute erfasst",
  todayAddLabel: "Salawat hinzufügen",
  todayAddHint: "Gib eine ganze Zahl ein.",
  todaySubmit: "Eintragen",
  todayDashboard: "Übersicht",
  todayTotal: "Gesamt",
  todayWeek: "Diese Woche",
  todayGoal: "Tagesziel",
  todayGoalDays: "Ziel erreicht",
  todayNoGoal: "Kein Ziel",
  todayNoGoalDay: "Noch kein Zieltag",
  todayHistory: "Verlauf",
  todayHistoryEmpty: "Noch keine Einträge vorhanden.",
  goalTitle: "Tagesziel",
  goalSliderLabel: "Tagesziel-Regler",
  goalSliderHint: "Passe das Tagesziel in 100er-Schritten bis 10.000 an.",
  goalAmountLabel: "Zielwert",
  goalAmountHint: "Gib eine ganze Zahl von 1 bis 10.000.000 ein.",
  goalSave: "Ziel speichern",
  goalClear: "Ziel deaktivieren",
  goalSaveFailed: "Das Tagesziel konnte nicht gespeichert werden. Versuche es erneut.",
  historyLoadMore: "Weitere Einträge laden",
  historyLoadFailed: "Weitere Einträge konnten nicht geladen werden.",
  historyEnd: "Alle Einträge geladen.",
  entryEditTitle: "Eintrag bearbeiten",
  entryAmountLabel: "Betrag",
  entryAmountInvalid: "Gib eine ganze Zahl von 1 bis 10.000.000 ein.",
  entryDateLabel: "Datum",
  entryDateInvalid: "Wähle ein Datum von heute oder höchstens 365 Tage davor.",
  entrySaveFailed: "Der Eintrag konnte nicht gespeichert werden. Versuche es erneut.",
  entryConflict:
    "Dieser Eintrag wurde auf einem anderen Gerät geändert.",
  entryDeleteConflict:
    "Dieser Eintrag wurde vor dem Löschen auf einem anderen Gerät geändert.",
  entryConflictServer: "Serverstand",
  entryConflictLocal: "Meine Änderung",
  entryConflictKeepServer: "Serverstand behalten",
  entryConflictReapply: "Meine Änderung erneut anwenden",
  entrySyncPending: "Ausstehend",
  entrySyncSynced: "Synchronisiert",
  entrySyncFailed: "Synchronisierung fehlgeschlagen",
  entrySyncConflict: "Konflikt",
  entryToday: "Heute",
  entryYesterday: "Gestern",
  entryEdit: "Bearbeiten",
  entryResolveConflict: "Konflikt lösen",
  entryDelete: "Löschen",
  entryDeleteTitle: "Eintrag löschen?",
  entryDeleteBody: "Dieser Eintrag wird endgültig gelöscht.",
  entryDeleteConfirm: "Löschen",
  commonCancel: "Abbrechen",
  groupsCreate: "Gruppe erstellen",
  groupsJoinManualCode: "Einladungscode eingeben",
  groupsEmptyTitle: "Noch keine Gruppe",
  groupsEmptyBody:
    "Du bist noch in keiner Gruppe. Erstelle eine private Gruppe oder tritt über einen Einladungslink bei.",
  groupCreateTitle: "Gruppe erstellen",
  groupNameLabel: "Gruppenname",
  groupNameHint: "2 bis 50 sichtbare Zeichen.",
  groupNameInvalid: "Der Gruppenname muss 2 bis 50 Zeichen lang sein.",
  groupTimezoneLabel: "Zeitzone",
  groupTimezoneHint: "IANA-Zeitzone, zum Beispiel Europe/Berlin.",
  groupTimezoneInvalid: "Bitte gib eine gültige IANA-Zeitzone ein.",
  groupCreateAnonymousLabel: "Rangliste anonym anzeigen",
  groupCreateAnonymousHint:
    "Andere Mitglieder sehen dann stabile Aliasnamen statt Anzeigenamen.",
  groupCreateAnonymousCaveat:
    "Hinweis: Wenn jemand die Rangliste vorher mit Anzeigenamen gesehen hat, wirkt die Anonymisierung nicht rückwirkend.",
  groupCreateRulesLabel:
    "Ich akzeptiere die Nutzungsbedingungen und Gruppenregeln.",
  groupCreateRulesHint:
    "Mein Anzeigename und aggregierte Salawat-Werte werden mit aktiven Gruppenmitgliedern geteilt.",
  groupCreateLegalAction: "Nutzungsbedingungen und Regeln öffnen",
  groupCreateLegalActionHint:
    "Öffnet die rechtlichen Hinweise und Nutzungsbedingungen.",
  groupCreateErrorOffline:
    "Du bist offline. Verbinde dich und versuche es erneut.",
  groupCreateErrorNameRejected:
    "Dieser Gruppenname ist nicht zulässig. Bitte wähle einen anderen Namen.",
  groupCreateErrorGroupLimitReached:
    "Du hast das Gruppenlimit erreicht. Verlasse eine bestehende Gruppe oder versuche es später erneut.",
  groupCreateErrorConsentRequired:
    "Bitte bestätige die Gruppenregeln, um fortzufahren.",
  groupCreateErrorRateLimited:
    "Zu viele Versuche. Bitte warte kurz und versuche es erneut.",
  groupCreateErrorInvalidInput:
    "Diese Zeitzone wurde nicht akzeptiert. Prüfe das Format, zum Beispiel Europe/Berlin.",
  groupCreateErrorGeneral:
    "Die Gruppe konnte nicht erstellt werden. Bitte versuche es erneut.",
  groupsListLoadingTitle: "Gruppen werden geladen",
  groupsListLoadingBody: "Wir holen den aktuellen Serverstand.",
  groupsListErrorTitle: "Gruppen konnten nicht geladen werden",
  groupsListErrorBody: "Bitte versuche es erneut.",
  groupsListOfflineTitle: "Offline",
  groupsListOfflineBody:
    "Verbinde dich mit dem Internet, um Gruppen zu laden.",
  groupsListRefresh: "Aktualisieren",
  groupsListWeekTotalLabel: "Diese Woche",
  groupsListRankLabel: "Rang",
  groupsListRankUnranked: "ohne Rang",
  groupsListMembersLabel: "aktive Mitglieder",
  groupsListCalculatedLabel: "Berechnet",
  groupsListUpdatedLabel: "Aktualisiert",
  groupsListAnonymousOn: "Anonyme Rangliste aktiv",
  groupsListAnonymousOff: "Rangliste mit Anzeigenamen",
  groupTitle: "Private Gruppe",
  groupDetailTitle: "Gruppendetail",
  groupRanking: "Rangliste",
  groupMembers: "Mitglieder verwalten",
  groupInvites: "Einladungen verwalten",
  groupDetailWeek: "Woche",
  groupDetailAllTime: "Gesamt",
  groupDetailMembersLabel: "aktive Mitglieder",
  groupDetailCalculatedLabel: "Zuletzt berechnet",
  groupDetailCalculatedUnknown: "Noch nicht berechnet",
  groupDetailLoadMore: "Mehr laden",
  groupDetailEnd: "Alle Plätze geladen.",
  groupDetailEmptyTitle: "Noch keine Rangliste",
  groupDetailEmptyBody: "Sobald Werte vorhanden sind, erscheinen sie hier.",
  groupDetailLoadingTitle: "Rangliste wird geladen",
  groupDetailLoadingBody: "Wir holen den aktuellen Gruppenstand.",
  groupDetailOfflineTitle: "Offline",
  groupDetailOfflineBody:
    "Du bist offline. Verbinde dich und aktualisiere die Rangliste.",
  groupDetailRateLimitedTitle: "Bitte kurz warten",
  groupDetailRateLimitedBody:
    "Zu viele Anfragen. Versuche es in einem Moment erneut.",
  groupDetailNotFoundTitle: "Gruppe nicht gefunden",
  groupDetailNotFoundBody:
    "Diese Gruppe ist nicht mehr verfügbar oder du hast keinen Zugriff.",
  groupDetailConflictTitle: "Änderungskonflikt",
  groupDetailConflictBody:
    "Inzwischen gibt es einen neueren Stand. Bitte aktualisiere die Rangliste.",
  groupDetailErrorTitle: "Rangliste konnte nicht geladen werden",
  groupDetailErrorBody: "Bitte versuche es erneut.",
  groupDetailRefresh: "Aktualisieren",
  groupDetailSelfLabel: "Du",
  groupDetailAnonymityOwnerLabel: "Rangliste anonym anzeigen",
  groupDetailAnonymityOwnerHint:
    "Wenn aktiviert, siehst du deinen echten Anzeigenamen, andere sehen deinen stabilen Gruppenalias.",
  groupDetailAnonymityAliasPrefix: "Dein Alias in dieser Gruppe",
  groupDetailAnonymityCaveat:
    "Hinweis: Bereits gesehene Anzeigenamen lassen sich nicht rückwirkend verbergen.",
  groupDetailAnonymityMemberStatusOn: "Anonyme Rangliste ist aktiv.",
  groupDetailAnonymityMemberStatusOff: "Rangliste zeigt Anzeigenamen.",
  groupDetailAnonymityConflict:
    "Zwischenzeitlich wurde eine neuere Änderung gespeichert. Wir laden den aktuellen Stand neu.",
  groupDetailAnonymityRevisionMissing:
    "Die Einstellung konnte nicht gespeichert werden. Bitte aktualisiere die Gruppe und versuche es erneut.",
  groupDetailInviteAction: "Einladungen verwalten",
  groupMembersTitle: "Mitglieder",
  groupInvitesTitle: "Einladungen",
  groupInvitesCreateAction: "Neue Einladung erstellen",
  groupInvitesLoadingTitle: "Einladungen werden geladen",
  groupInvitesLoadingBody: "Wir holen den aktuellen Gruppenstand.",
  groupInvitesEmptyTitle: "Noch keine Einladung",
  groupInvitesEmptyBody:
    "Erstelle eine Einladung und teile sie mit deiner Gruppe.",
  groupInvitesRefresh: "Aktualisieren",
  groupInvitesOfflineTitle: "Offline",
  groupInvitesOfflineBody:
    "Verbinde dich mit dem Internet, um Einladungen zu verwalten.",
  groupInvitesRateLimitedTitle: "Bitte kurz warten",
  groupInvitesRateLimitedBody:
    "Zu viele Aktionen in kurzer Zeit. Versuche es gleich erneut.",
  groupInvitesErrorTitle: "Einladungen konnten nicht geladen werden",
  groupInvitesErrorBody: "Bitte versuche es erneut.",
  groupInvitesNotFoundTitle: "Einladung nicht gefunden",
  groupInvitesNotFoundBody:
    "Diese Einladung ist nicht mehr verfügbar. Aktualisiere die Liste.",
  groupInvitesActionErrorTitle: "Aktion fehlgeschlagen",
  groupInvitesActionErrorBody:
    "Die Aktion konnte nicht abgeschlossen werden. Bitte versuche es erneut.",
  groupInvitesStatusActive: "Aktiv",
  groupInvitesStatusExpired: "Abgelaufen",
  groupInvitesStatusExhausted: "Verbraucht",
  groupInvitesStatusRevoked: "Widerrufen",
  groupInvitesUseLabel: "Nutzungen",
  groupInvitesExpiryLabel: "Ablauf",
  groupInvitesSecretTitle: "Neue Einladung",
  groupInvitesSecretBody:
    "Teile Link und Code nur mit Personen, die der privaten Gruppe beitreten sollen.",
  groupInvitesSecretLinkLabel: "Einladungslink",
  groupInvitesSecretCodeLabel: "Einladungscode",
  groupInvitesShareAction: "Teilen",
  groupInvitesCopyLinkAction: "Link kopieren",
  groupInvitesCopyCodeAction: "Code kopieren",
  groupInvitesDismissSecretAction: "Schließen",
  groupInvitesRevokeAction: "Widerrufen",
  groupInvitesRevokeConfirmTitle: "Einladung widerrufen?",
  groupInvitesRevokeConfirmBody:
    "Diese Einladung kann danach nicht mehr verwendet werden.",
  groupInvitesShareMessage:
    "Tritt unserer privaten Gruppe bei.\nLink: %{link}\nCode: %{code}",
  joinTitle: "Einladung prüfen",
  joinBody: "Prüfe die Gruppeninformationen, bevor du freiwillig beitrittst.",
  joinAction: "Einladung annehmen",
  joinManualCodeTitle: "Einladungscode eingeben",
  joinManualCodeLabel: "Einladungscode",
  joinManualCodeHint: "10 Zeichen, Buchstaben und Zahlen ohne 0, O, 1, I, L.",
  joinManualCodeSubmit: "Einladung prüfen",
  joinPreviewHeading: "Gruppenvorschau",
  joinMembersLabel: "aktive Mitglieder",
  joinSharingExplanation:
    "Mit dem Beitritt werden dein Anzeigename und aggregierte Salawat-Werte für aktive Mitglieder sichtbar.",
  joinAnonymityOn:
    "Aktuell sehen andere Mitglieder deinen Alias, während du selbst deinen Anzeigenamen siehst. Der Gruppeninhaber kann diese Einstellung später ändern.",
  joinAnonymityOff:
    "Aktuell sehen aktive Mitglieder deinen Anzeigenamen und aggregierte Salawat-Werte.",
  joinNoShareBeforeConfirm: "Vor deiner Bestätigung werden keine Werte geteilt.",
  joinAlreadyActiveHint:
    "Du bist bereits aktives Mitglied. Mit Bestätigen kommst du direkt zur Gruppe.",
  joinLoadingTitle: "Einladung wird geprüft",
  joinLoadingBody: "Wir laden die aktuellen Gruppendaten.",
  joinErrorTitle: "Einladung nicht verfügbar",
  joinInvalidInviteMessage: "Diese Einladung ist nicht mehr gültig.",
  joinRateLimitedMessage:
    "Zu viele Versuche. Bitte warte kurz und versuche es erneut.",
  joinOfflineMessage:
    "Du bist offline. Verbinde dich mit dem Internet und versuche es erneut.",
  joinErrorMessage: "Die Einladung konnte nicht geladen werden. Bitte versuche es erneut.",
  joinRefresh: "Erneut prüfen",
  joinStorageRetry: "Erneut versuchen",
  joinAbandonAction: "Einladung verwerfen",
  joinAbandonTitle: "Einladung verwerfen?",
  joinAbandonBody:
    "Der gespeicherte Einladungslink wird von diesem Gerät entfernt. Du kannst ihn später nur über den ursprünglichen Link erneut öffnen.",
  joinExitAction: "Zur Übersicht",
  settingsLanguage: "Sprache",
  settingsLanguageHint: "Sprache dieser App",
  settingsLanguageSystem: "Systemstandard",
  settingsLanguageGerman: "Deutsch",
  settingsLanguageEnglish: "English",
  settingsProfile: "Profil",
  settingsReminder: "Tägliche Erinnerung",
  settingsPrivacy: "Datenschutz",
  settingsLegal: "Rechtliches",
  settingsSupport: "Hilfe und Support",
  settingsSignOut: "Abmelden",
  settingsSignOutFailed: "Die lokalen Kontodaten konnten nicht vollständig gelöscht werden.",
  reminderTitle: "Tägliche Erinnerung",
  reminderTimeLabel: "Uhrzeit",
  privacyTitle: "Datenschutz",
  privacyExport: "Daten exportieren",
  privacyDelete: "Konto löschen",
  legalTitle: "Rechtliches",
  legalPrivacy: "Datenschutzerklärung",
  legalTerms: "Nutzungsbedingungen",
  legalImprint: "Impressum",
  supportTitle: "Hilfe und Support",
  supportReport: "Problem melden",
  supportContact: "Kontakt aufnehmen",
  stateLoadingTitle: "Wird geladen",
  stateLoadingBody: "Einen Moment bitte.",
  stateEmptyTitle: "Noch keine Inhalte",
  stateEmptyBody: "Hier erscheint etwas, sobald Daten vorhanden sind.",
  stateOfflineWithDataTitle: "Offline",
  stateOfflineWithDataBody: "Du siehst den zuletzt gespeicherten Stand.",
  stateOfflineEmptyTitle: "Offline und noch keine Daten",
  stateOfflineEmptyBody: "Stelle eine Verbindung her und versuche es erneut.",
  statePendingTitle: "Wird synchronisiert",
  statePendingBody: "Deine Änderung bleibt sicher auf diesem Gerät.",
  syncOfflineTitle: "Offline",
  syncOfflineBody: "Änderungen bleiben verschlüsselt auf diesem Gerät.",
  syncPendingTitle: "Wird synchronisiert",
  syncPendingBody: "Deine Änderungen sind lokal gespeichert.",
  syncFailedTitle: "Synchronisierung fehlgeschlagen",
  syncFailedBody: "Einige Änderungen brauchen deine Aufmerksamkeit.",
  syncConflictTitle: "Änderungskonflikt",
  syncConflictBody: "Prüfe den betroffenen Eintrag, bevor du fortfährst.",
  syncRetry: "Erneut versuchen",
  offlineRecoveryTitle: "Lokale Daten konnten nicht gelesen werden",
  offlineRecoveryBody:
    "Setze den lokalen Speicher zurück und lade deine synchronisierten Daten neu.",
  offlineRecoveryAction: "Lokalen Speicher zurücksetzen",
  offlineRecoveryConfirmTitle: "Lokale Daten zurücksetzen?",
  offlineRecoveryConfirmBody:
    "Nicht synchronisierte Einträge und Zieländerungen auf diesem Gerät gehen verloren. Bereits synchronisierte Daten werden anschließend erneut vom Server geladen.",
  offlineRecoveryConfirmAction: "Zurücksetzen",
  offlineLoadRetryTitle: "Lokale Daten sind gerade nicht verfügbar",
  offlineLoadRetryBody:
    "Der lokale Speicher konnte nicht geladen werden. Versuche es erneut.",
  offlineLoadRetryAction: "Erneut laden",
  statePartialErrorTitle: "Nicht alles konnte geladen werden",
  statePartialErrorBody: "Die vorhandenen Inhalte bleiben sichtbar.",
  stateErrorTitle: "Verbindung nicht möglich",
  stateErrorBody: "Versuche es in einem Moment erneut.",
  stateForbiddenTitle: "Kein Zugriff",
  stateForbiddenBody: "Du darfst diesen Inhalt nicht öffnen.",
  stateSessionExpiredTitle: "Sitzung abgelaufen",
  stateSessionExpiredBody: "Melde dich erneut an.",
  stateMaintenanceTitle: "Wartung läuft",
  stateMaintenanceBody: "Salawat Circle ist bald wieder verfügbar.",
  stateUpgradeRequiredTitle: "Aktualisierung erforderlich",
  stateUpgradeRequiredBody: "Aktualisiere die App, um fortzufahren.",
  notFoundTitle: "Seite nicht gefunden",
  notFoundBody: "Diese Seite ist nicht verfügbar.",
  notFoundAction: "Zur Willkommensseite",
} as const;
export type TranslationKey = keyof typeof de;
