import type { TranslationKey } from "./de";
export const en = {
  appName: "Salawat Circle",
  commonContinue: "Continue",
  commonSave: "Save",
  commonUnavailable: "Not available in this MVP yet",
  tabsToday: "Today",
  tabsGroups: "Groups",
  tabsSettings: "Settings",
  welcomeEyebrow: "Private and data-minimizing",
  welcomeTitle: "Record Salawat mindfully",
  welcomeBody:
    "Record your personal values and only share aggregated numbers voluntarily in private groups.",
  welcomeAction: "Start sign-in",
  authEmailTitle: "Email address",
  authEmailLabel: "Email address",
  authEmailHint: "We will send you a one-time sign-in code.",
  authEmailAction: "Continue to code",
  authEmailInvalid: "Enter a valid email address.",
  authRequestFailed: "The code could not be requested. Try again later.",
  authCodeTitle: "One-time code",
  authCodeLabel: "Six-digit code",
  authCodeHint: "The code is valid for ten minutes.",
  authCodeSent:
    "If the address can be used, a sign-in code has been sent.",
  authCodeAction: "Verify code",
  authCodeInvalid: "The code is invalid or no longer valid.",
  authCodeResend: "Request a new code",
  authCodeResendIn: "Request again in",
  profileTitle: "Your profile",
  profileNameLabel: "Display name",
  profileNameHint: "Between 2 and 30 characters.",
  profileNameInvalid: "The display name must be 2 to 30 characters long.",
  profileTimezoneLabel: "Time zone",
  profileTimezoneHint: "Detected automatically as an IANA time zone.",
  profileSaveFailed: "The profile could not be saved.",
  consentTitle: "Consent",
  consentBody:
    "Salawat Circle processes your display name, time zone, and personal Salawat entries to provide your private account and statistics. This consent does not include sharing with groups; you decide that separately whenever you join one.",
  consentLabel: "I consent to processing my personal entries.",
  consentHint: "Sharing with groups remains voluntary.",
  consentSaveFailed: "Consent could not be saved.",
  todayHeading: "Recorded today",
  todayAddLabel: "Add Salawat",
  todayAddHint: "Enter a whole number.",
  todaySubmit: "Record",
  todayDashboard: "Overview",
  todayTotal: "Total",
  todayWeek: "This week",
  todayGoal: "Daily goal",
  todayGoalDays: "Goal reached",
  todayNoGoal: "No goal",
  todayNoGoalDay: "No goal day yet",
  todayHistory: "History",
  todayHistoryEmpty: "No entries yet.",
  goalTitle: "Daily goal",
  goalSliderLabel: "Daily goal slider",
  goalSliderHint: "Adjust the daily goal in steps of 100 up to 10,000.",
  goalAmountLabel: "Goal amount",
  goalAmountHint: "Enter a whole number from 1 to 10,000,000.",
  goalSave: "Save goal",
  goalClear: "Disable goal",
  goalSaveFailed: "The daily goal could not be saved. Try again.",
  historyLoadMore: "Load more entries",
  historyLoadFailed: "More entries could not be loaded.",
  historyEnd: "All entries loaded.",
  entryEditTitle: "Edit entry",
  entryAmountLabel: "Amount",
  entryAmountInvalid: "Enter a whole number from 1 to 10,000,000.",
  entryDateLabel: "Date",
  entryDateInvalid: "Choose today or a date no more than 365 days ago.",
  entrySaveFailed: "The entry could not be saved. Try again.",
  entryConflict:
    "This entry was changed on another device.",
  entryDeleteConflict:
    "This entry was changed on another device before it was deleted.",
  entryConflictServer: "Server version",
  entryConflictLocal: "My change",
  entryConflictKeepServer: "Keep server version",
  entryConflictReapply: "Apply my change again",
  entrySyncPending: "Pending",
  entrySyncSynced: "Synced",
  entrySyncFailed: "Sync failed",
  entrySyncConflict: "Conflict",
  entryToday: "Today",
  entryYesterday: "Yesterday",
  entryEdit: "Edit",
  entryDelete: "Delete",
  entryDeleteTitle: "Delete entry?",
  entryDeleteBody: "This entry will be permanently deleted.",
  entryDeleteConfirm: "Delete",
  commonCancel: "Cancel",
  groupsCreate: "Create group",
  groupsEmptyTitle: "No group yet",
  groupsEmptyBody:
    "You are not in a group yet. Create a private group or join through an invitation link.",
  groupCreateTitle: "Create group",
  groupNameLabel: "Group name",
  groupNameHint: "2 to 50 visible characters.",
  groupNameInvalid: "The group name must be 2 to 50 characters long.",
  groupTimezoneLabel: "Time zone",
  groupTimezoneHint: "IANA time zone, for example Europe/Berlin.",
  groupTimezoneInvalid: "Enter a valid IANA time zone.",
  groupCreateAnonymousLabel: "Show the ranking anonymously",
  groupCreateAnonymousHint:
    "Other members will then see stable aliases instead of display names.",
  groupCreateAnonymousCaveat:
    "Note: if someone has already seen the ranking with display names, anonymity is not retroactive.",
  groupCreateRulesLabel: "I accept the terms of use and group rules.",
  groupCreateRulesHint:
    "My display name and aggregated Salawat values are shared with active group members.",
  groupCreateLegalAction: "Open terms and group rules",
  groupCreateLegalActionHint:
    "Opens the legal details and terms of use.",
  groupCreateErrorOffline: "You are offline. Connect and try again.",
  groupCreateErrorNameRejected:
    "This group name is not allowed. Please choose another name.",
  groupCreateErrorGroupLimitReached:
    "You have reached the group limit. Leave an existing group or try again later.",
  groupCreateErrorConsentRequired:
    "Please confirm the group rules to continue.",
  groupCreateErrorRateLimited:
    "Too many attempts. Please wait a moment and try again.",
  groupCreateErrorInvalidInput:
    "This time zone was rejected. Check the format, for example Europe/Berlin.",
  groupCreateErrorGeneral:
    "The group could not be created. Please try again.",
  groupsListLoadingTitle: "Loading groups",
  groupsListLoadingBody: "Fetching the latest server state.",
  groupsListErrorTitle: "Groups could not be loaded",
  groupsListErrorBody: "Please try again.",
  groupsListOfflineTitle: "Offline",
  groupsListOfflineBody: "Connect to the internet to load groups.",
  groupsListRefresh: "Refresh",
  groupsListWeekTotalLabel: "This week",
  groupsListRankLabel: "Rank",
  groupsListRankUnranked: "unranked",
  groupsListMembersLabel: "active members",
  groupsListCalculatedLabel: "Calculated",
  groupsListUpdatedLabel: "Updated",
  groupsListAnonymousOn: "Anonymous ranking enabled",
  groupsListAnonymousOff: "Ranking with display names",
  groupTitle: "Private group",
  groupRanking: "Ranking",
  groupMembers: "Manage members",
  groupInvites: "Manage invitations",
  groupMembersTitle: "Members",
  groupInvitesTitle: "Invitations",
  joinTitle: "Review invitation",
  joinBody: "Review the group information before joining voluntarily.",
  joinAction: "Accept invitation",
  settingsLanguage: "Language",
  settingsLanguageHint: "Language for this app",
  settingsLanguageSystem: "System default",
  settingsLanguageGerman: "Deutsch",
  settingsLanguageEnglish: "English",
  settingsProfile: "Profile",
  settingsReminder: "Daily reminder",
  settingsPrivacy: "Privacy",
  settingsLegal: "Legal",
  settingsSupport: "Help and support",
  settingsSignOut: "Sign out",
  settingsSignOutFailed: "Local account data could not be removed completely.",
  reminderTitle: "Daily reminder",
  reminderTimeLabel: "Time",
  privacyTitle: "Privacy",
  privacyExport: "Export data",
  privacyDelete: "Delete account",
  legalTitle: "Legal",
  legalPrivacy: "Privacy policy",
  legalTerms: "Terms of use",
  legalImprint: "Legal notice",
  supportTitle: "Help and support",
  supportReport: "Report a problem",
  supportContact: "Contact support",
  stateLoadingTitle: "Loading",
  stateLoadingBody: "Please wait a moment.",
  stateEmptyTitle: "No content yet",
  stateEmptyBody: "Content will appear here once it is available.",
  stateOfflineWithDataTitle: "Offline",
  stateOfflineWithDataBody: "You are seeing the last saved state.",
  stateOfflineEmptyTitle: "Offline with no saved data",
  stateOfflineEmptyBody: "Connect to the internet and try again.",
  statePendingTitle: "Syncing",
  statePendingBody: "Your change remains safely stored on this device.",
  syncOfflineTitle: "Offline",
  syncOfflineBody: "Changes remain encrypted on this device.",
  syncPendingTitle: "Syncing",
  syncPendingBody: "Your changes are stored locally.",
  syncFailedTitle: "Sync failed",
  syncFailedBody: "Some changes need your attention.",
  syncConflictTitle: "Change conflict",
  syncConflictBody: "Review the affected entry before continuing.",
  syncRetry: "Try again",
  statePartialErrorTitle: "Some content could not load",
  statePartialErrorBody: "Available content remains visible.",
  stateErrorTitle: "Unable to connect",
  stateErrorBody: "Try again in a moment.",
  stateForbiddenTitle: "No access",
  stateForbiddenBody: "You are not allowed to open this content.",
  stateSessionExpiredTitle: "Session expired",
  stateSessionExpiredBody: "Sign in again.",
  stateMaintenanceTitle: "Maintenance in progress",
  stateMaintenanceBody: "Salawat Circle will be available again soon.",
  stateUpgradeRequiredTitle: "Update required",
  stateUpgradeRequiredBody: "Update the app to continue.",
  notFoundTitle: "Page not found",
  notFoundBody: "This page is not available.",
  notFoundAction: "Go to welcome",
} as const satisfies Record<TranslationKey, string>;
