import type { TranslationKey } from "./de";
export const en = {
  appName: "Salawat Circle",
  commonContinue: "Continue",
  commonSave: "Save",
  commonEdit: "Edit",
  commonDelete: "Delete",
  commonConfirm: "Confirm",
  commonUnavailable: "Not available in this MVP yet",
  tabsToday: "Today",
  tabsGroups: "Groups",
  tabsSettings: "Settings",
  welcomeEyebrow: "Private and data-minimizing",
  welcomeTitle: "Record Salawat mindfully",
  welcomeBody:
    "Record your personal values and only share aggregated numbers voluntarily in private groups.",
  welcomeAction: "Start sign-in",
  authEmailTitle: "Email address",
  authEmailLabel: "Email address",
  authEmailHint: "We will send you a one-time sign-in code.",
  authEmailAction: "Continue to code",
  authCodeTitle: "One-time code",
  authCodeLabel: "Six-digit code",
  authCodeHint: "The code is valid for ten minutes.",
  authCodeResend: "Request a new code",
  profileTitle: "Your profile",
  profileNameLabel: "Display name",
  profileTimezoneLabel: "Time zone",
  consentTitle: "Consent",
  consentLabel: "I consent to processing my personal entries.",
  consentHint: "Sharing with groups remains voluntary.",
  todayHeading: "Recorded today",
  todayAddLabel: "Add Salawat",
  todayAddHint: "Enter a whole number.",
  todaySubmit: "Record",
  todayDashboard: "Overview",
  todayTotal: "Total",
  todayWeek: "This week",
  todayGoal: "Daily goal",
  todayGoalDays: "Goal reached",
  todayNoGoal: "No goal",
  todayNoGoalDay: "No goal day yet",
  todayHistory: "History",
  todayHistoryEmpty: "No entries yet.",
  goalAdjustTitle: "Adjust daily goal",
  goalSaveAction: "Save goal",
  goalDeactivateAction: "Deactivate goal",
  conflictTitle: "Revision conflict",
  conflictBody: "This entry was modified on another device.",
  conflictKeepServer: "Keep server version",
  conflictReapplyMine: "Reapply my change",
  statusPendingBadge: "Pending",
  statusConflictBadge: "Conflict",
  entryEditTitle: "Edit entry",
  entryAmountLabel: "Amount",
  entryDateLabel: "Date",
  groupsCreate: "Create group",
  groupsEmptyTitle: "No group yet",
  groupsEmptyBody:
    "You are not in a group yet. Create a private group or join through an invitation link.",
  groupCreateTitle: "Create group",
  groupNameLabel: "Group name",
  groupTitle: "Private group",
  groupRanking: "Ranking",
  groupMembers: "Manage members",
  groupInvites: "Manage invitations",
  groupMembersTitle: "Members",
  groupInvitesTitle: "Invitations",
  joinTitle: "Review invitation",
  joinBody: "Review the group information before joining voluntarily.",
  joinAction: "Accept invitation",
  settingsLanguage: "Language",
  settingsLanguageHint: "Language for this app",
  settingsLanguageGerman: "Deutsch",
  settingsLanguageEnglish: "English",
  settingsLanguageSystem: "System default",
  settingsProfile: "Profile",
  settingsReminder: "Daily reminder",
  settingsPrivacy: "Privacy",
  settingsLegal: "Legal",
  settingsSupport: "Help and support",
  reminderTitle: "Daily reminder",
  reminderTimeLabel: "Time",
  privacyTitle: "Privacy",
  privacyExport: "Export data",
  privacyDelete: "Delete account",
  legalTitle: "Legal",
  legalPrivacy: "Privacy policy",
  legalTerms: "Terms of use",
  legalImprint: "Legal notice",
  supportTitle: "Help and support",
  supportReport: "Report a problem",
  supportContact: "Contact support",
  stateLoadingTitle: "Loading",
  stateLoadingBody: "Please wait a moment.",
  stateEmptyTitle: "No content yet",
  stateEmptyBody: "Content will appear here once it is available.",
  stateOfflineWithDataTitle: "Offline",
  stateOfflineWithDataBody: "You are seeing the last saved state.",
  stateOfflineEmptyTitle: "Offline with no saved data",
  stateOfflineEmptyBody: "Connect to the internet and try again.",
  statePendingTitle: "Syncing",
  statePendingBody: "Your change remains safely stored on this device.",
  statePartialErrorTitle: "Some content could not load",
  statePartialErrorBody: "Available content remains visible.",
  stateErrorTitle: "Unable to connect",
  stateErrorBody: "Try again in a moment.",
  stateForbiddenTitle: "No access",
  stateForbiddenBody: "You are not allowed to open this content.",
  stateSessionExpiredTitle: "Session expired",
  stateSessionExpiredBody: "Sign in again.",
  stateMaintenanceTitle: "Maintenance in progress",
  stateMaintenanceBody: "Salawat Circle will be available again soon.",
  stateUpgradeRequiredTitle: "Update required",
  stateUpgradeRequiredBody: "Update the app to continue.",
  notFoundTitle: "Page not found",
  notFoundBody: "This page is not available.",
  notFoundAction: "Go to welcome",
} as const satisfies Record<TranslationKey, string>;
